version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-205-27.compute-1.amazonaws.com
            database: d57ilod88vaudr
            user: cyxopauzdivnfw
            password: 5dcc6e2d621a74144b6faf368fb2b900d7d819cb0c1165a0c7e39baf963b816d
            rawAccess: true
            port: '5432'
            migrations: true
            ssl: true