version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-196-179.compute-1.amazonaws.com
            database: de3q8fun4dcc29
            user: gztwbbxogukzll
            password: 56a7574fba0c194071e061b006204c7f970212facd9e90af98ae7f96c0ab6d76
            rawAccess: true
            port: '5432'
            migrations: true
            ssl: true